### ISSUE TITLE
A domain is missing

### ISSUE THREAD

**Issue by MaXfAa** [nickspaargaren/no-amazon#28]
If I saw correctly, "amzn.to" is missing...

**Comment by nickspaargaren** [comment]
Thank you @MaXfAa and @gallegonovato!

**Comment by gallegonovato** [comment]
Good afternoon @nickspaargaren 

There is no need to give them. We are here to help you. :) 👍 

Thanks also to @MaXfAa for also noticing the deletion of this entry and roasting. 👍 

Best regards
