### ISSUE TITLE
regex list

### ISSUE THREAD

**Issue by Raj52537** [nickspaargaren/no-amazon#4]
Sir
Thanks for good list
I want to know how to create regex list for other hosts
I want it for energized ultimate and Microsoft

**Comment by gallegonovato** [comment]
Good afternoon @Raj52537

About energized you have their lists at https://github.com/EnergizedProtection/block

Then about Microsoft you could make a hosts. If @nickspaargaren is ok with that. But they are a lot of entries. And then there are applications to remove things from telemetry and that Microsoft adds more.

A hug
