### ISSUE TITLE
www.amazon.amazon and www.amazon.yamaxun and more

### ISSUE THREAD

**Issue by tj-commits** [nickspaargaren/no-amazon#46]
according to networksdb.io, these do not exist (they are not in the lists)
https://networksdb.io/get/domain-lists/amazon
https://networksdb.io/get/domain-lists/yamaxun

also, upon checking, there are more like this that don't exist:
www.amazon.amazon
www.amazon.app
www.amazon.audible
www.amazon.author
www.amazon.aws
www.amazon.book
www.amazon.box
www.amazon.buy
www.amazon.circle
www.amazon.coupon
www.amazon.deal
www.amazon.dev
www.amazon.drive
www.amazon.fast
www.amazon.fire
www.amazon.free
www.amazon.game
www.amazon.got
www.amazon.group
www.amazon.hot
www.amazon.imdb
www.amazon.jot
www.amazon.joy
www.amazon.kids
www.amazon.kindle
www.amazon.like
www.amazon.mail (the .mail extension doesn't even exist!)
www.amazon.map
www.amazon.mobile
www.amazon.moi
www.amazon.music
www.amazon.now
www.amazon.pay
www.amazon.pin
www.amazon.play
www.amazon.read
www.amazon.room
www.amazon.safe
www.amazon.save
www.amazon.search
www.amazon.secure
www.amazon.silk
www.amazon.smile
www.amazon.song
www.amazon.spot
www.amazon.talk
www.amazon.tunes
www.amazon.tushu
www.amazon.wanggou
www.amazon.wow
www.amazon.yamaxun
www.amazon.you
www.amazon.yun
www.amazon.zappos

**Comment by nickspaargaren** [comment]
Thanks @tj-commits! I've run all domains against whois and turns out there are a few valid domains!

Looks like these are valid:

```
amazon.app
amazon.dev
amazon.game
amazon.moi
ads.amazon
alexa.amazon
echo.amazon
grandchallenge.amazon
kindle.amazon
monitor-nominet.amazon
nic.amazon
pharmacy.amazon
pharmacyservices.amazon
prime.amazon
primevideo.amazon
projectkuiper.amazon
nic.yamaxun
monitor-nominet.yamaxun
```

Pull request incoming..

**Comment by tj-commits** [comment]
@nickspaargaren Your welcome
