### ISSUE TITLE
The content(z)

### ISSUE THREAD

**Issue by ghost** [nickspaargaren/no-amazon#50]
the content(z).mkt(number).(net/com) are missing a few. Here's the updated list:
content.mkt51.net
content.mkt61.net
content.mkt912.com
content.mkt922.com
content.mkt931.com
content.mkt932.com
content.mkt941.com
contentz.mkt51.net
contentz.mkt61.net
contentz.mkt912.com
contentz.mkt922.com
contentz.mkt931.com
contentz.mkt932.com
contentz.mkt941.com

**Comment by tj-commits** [comment]
@nickspaargaren

**Comment by nickspaargaren** [comment]
Actually these are not Amazons,

**Comment by nickspaargaren** [comment]
Thanks for the reminder @tj-commits, actually these are not Amazons, removed in https://github.com/nickspaargaren/no-amazon/pull/54

https://www.whois.com/whois/mkt51.net
